#############################################################################
# Makefile for building: CircularBuffer
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  CircularBuffer.pro
# Template: app
# Command: /opt/Qt5.3.1/5.3/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile CircularBuffer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I. -I/opt/Qt5.3.1/5.3/gcc_64/include -I/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia -I/opt/Qt5.3.1/5.3/gcc_64/include/QtNetwork -I/opt/Qt5.3.1/5.3/gcc_64/include/QtGui -I/opt/Qt5.3.1/5.3/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/Qt5.3.1/5.3/gcc_64 -Wl,-rpath,/opt/Qt5.3.1/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/opt/Qt5.3.1/5.3/gcc_64/lib -lQt5Multimedia -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Qt5.3.1/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		global.cpp \
		audiorecorder.cpp moc_Consumer.cpp \
		moc_audiorecorder.cpp
OBJECTS       = main.o \
		global.o \
		audiorecorder.o \
		moc_Consumer.o \
		moc_audiorecorder.o
DIST          = /opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/lex.prf \
		CircularBuffer.pro main.cpp \
		global.cpp \
		audiorecorder.cpp
QMAKE_TARGET  = CircularBuffer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = CircularBuffer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CircularBuffer.pro /opt/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/lex.prf \
		CircularBuffer.pro \
		/opt/Qt5.3.1/5.3/gcc_64/lib/libQt5Multimedia.prl \
		/opt/Qt5.3.1/5.3/gcc_64/lib/libQt5Gui.prl \
		/opt/Qt5.3.1/5.3/gcc_64/lib/libQt5Core.prl \
		/opt/Qt5.3.1/5.3/gcc_64/lib/libQt5Network.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile CircularBuffer.pro
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.3.1/5.3/gcc_64/mkspecs/features/lex.prf:
CircularBuffer.pro:
/opt/Qt5.3.1/5.3/gcc_64/lib/libQt5Multimedia.prl:
/opt/Qt5.3.1/5.3/gcc_64/lib/libQt5Gui.prl:
/opt/Qt5.3.1/5.3/gcc_64/lib/libQt5Core.prl:
/opt/Qt5.3.1/5.3/gcc_64/lib/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile CircularBuffer.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/CircularBuffer1.0.0 || mkdir -p .tmp/CircularBuffer1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/CircularBuffer1.0.0/ && $(COPY_FILE) --parents global.h Consumer.h Producer.h audiorecorder.h .tmp/CircularBuffer1.0.0/ && $(COPY_FILE) --parents main.cpp global.cpp audiorecorder.cpp .tmp/CircularBuffer1.0.0/ && (cd `dirname .tmp/CircularBuffer1.0.0` && $(TAR) CircularBuffer1.0.0.tar CircularBuffer1.0.0 && $(COMPRESS) CircularBuffer1.0.0.tar) && $(MOVE) `dirname .tmp/CircularBuffer1.0.0`/CircularBuffer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CircularBuffer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_Consumer.cpp moc_audiorecorder.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Consumer.cpp moc_audiorecorder.cpp
moc_Consumer.cpp: /opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QCoreApplication \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QThread \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QTime \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdatetime.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		global.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QSemaphore \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsemaphore.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioFormat \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudioformat.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qmultimedia.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioDeviceInfo \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudiodeviceinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudio.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioOutput \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudiooutput.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QBuffer \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbuffer.h \
		Consumer.h
	/opt/Qt5.3.1/5.3/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I/home/pclass/Desktop/xbee_qt/CircularBuffer -I/opt/Qt5.3.1/5.3/gcc_64/include -I/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia -I/opt/Qt5.3.1/5.3/gcc_64/include/QtNetwork -I/opt/Qt5.3.1/5.3/gcc_64/include/QtGui -I/opt/Qt5.3.1/5.3/gcc_64/include/QtCore Consumer.h -o moc_Consumer.cpp

moc_audiorecorder.cpp: /opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QBuffer \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbuffer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudio \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudio.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qmultimedia.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioInput \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudioinput.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudioformat.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudiodeviceinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioOutput \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudiooutput.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioDeviceInfo \
		audiorecorder.h
	/opt/Qt5.3.1/5.3/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I/home/pclass/Desktop/xbee_qt/CircularBuffer -I/opt/Qt5.3.1/5.3/gcc_64/include -I/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia -I/opt/Qt5.3.1/5.3/gcc_64/include/QtNetwork -I/opt/Qt5.3.1/5.3/gcc_64/include/QtGui -I/opt/Qt5.3.1/5.3/gcc_64/include/QtCore audiorecorder.h -o moc_audiorecorder.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp /opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QCoreApplication \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qeventloop.h \
		Consumer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QThread \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QTime \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdatetime.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		global.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QSemaphore \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsemaphore.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioFormat \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudioformat.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qmultimedia.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioDeviceInfo \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudiodeviceinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudio.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioOutput \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudiooutput.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QBuffer \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbuffer.h \
		Producer.h \
		audiorecorder.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudio \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioInput \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudioinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

global.o: global.cpp global.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QSemaphore \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsemaphore.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o global.o global.cpp

audiorecorder.o: audiorecorder.cpp audiorecorder.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QBuffer \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbuffer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudio \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudio.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qmultimedia.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioInput \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudioinput.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudioformat.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudiodeviceinfo.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioOutput \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/qaudiooutput.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtMultimedia/QAudioDeviceInfo \
		global.h \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/QSemaphore \
		/opt/Qt5.3.1/5.3/gcc_64/include/QtCore/qsemaphore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audiorecorder.o audiorecorder.cpp

moc_Consumer.o: moc_Consumer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Consumer.o moc_Consumer.cpp

moc_audiorecorder.o: moc_audiorecorder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audiorecorder.o moc_audiorecorder.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/pi || mkdir -p $(INSTALL_ROOT)/home/pi
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/pi/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/pi/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/pi/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

